CREATE TABLE Mechanic (
    id VARCHAR2(36) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    cnpj VARCHAR2(20) NOT NULL,
    phone VARCHAR2(20) NOT NULL,
    email VARCHAR2(255) NOT NULL
);