CREATE TABLE Mechanic (
  id RAW(16) PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  address VARCHAR2(255) NOT NULL,
  cnpj VARCHAR2(20) NOT NULL,
  phone VARCHAR2(20) NOT NULL,
  email VARCHAR2(255) NOT NULL
);